### ISSUE TITLE
Drag down to refresh views

### ISSUE THREAD

**Issue by LeGaryGary** [acolytec3/ArMob#21]
The following views could be refreshed on dragging down and releasing:
- All Transactions
- Data Transactions
- Web view

**Comment by acolytec3** [comment]
- [x] - All Transactions - b12c54053f9713299e0203adf04b9d7aa1ef595d
~~- [ ] - Data Transactions~~
- [x] - Web view

**Comment by acolytec3** [comment]
@LeGaryGary Do you see any value in the data transactions view anymore.  I'm tempted to just remove it entirely and perhaps replace with some sort of filtering mechanism.

**Comment by LeGaryGary** [comment]
If all transactions include data transactions then maybe its best to have just one transaction pane. I like the idea of being able to filter / search transactions, I think that would be very useful

**Comment by acolytec3** [comment]
Yeah, it's the same data set, though arrived at by different ways.  The data in the data transactions tab is pulled from a graphQL query so it's a lot faster.  To build the full transaction view, I have to get all the transactions and then individually retrieve each tx's details from a node and then build my internal datastore.  Shouldn't be too hard to add some filtering logic to that.  What would be better is if Arweave could just expand what's returnable by the graphQL stack.  That would simplify all the wallet logic a ton. Here's to hoping.

**Comment by LeGaryGary** [comment]
If graphql can provide tx ids then you could use that to build a simple list then get more details when its expanded

**Comment by acolytec3** [comment]
Issue is resolved now that data transactions will be removed.
