### ISSUE TITLE
Use ArweaveID to show names 

### ISSUE THREAD

**Issue by LeGaryGary** [acolytec3/ArMob#27]
Where the data is avaliable we can show peoples names instead of wallet IDs

**Comment by acolytec3** [comment]
Necessary steps:
- [x] - Add arweaveIdLookup method to libarweave
- [x] - Add to some sort of profile that will display your ArweaveID in the appBar on the wallet screen if you have an ArweaveID registered
- [x] - Add ArweaveID lookup to transaction details in wallet screens

**Comment by acolytec3** [comment]
Newest commit will lookup the arweave ID for the loaded address and display it in the app header if available.

**Comment by acolytec3** [comment]
Resolved by 6eb7e71a1593f90b67ad5ffb25ef7493edd59214
